# Generated by Django 5.1.4 on 2025-01-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_alter_transactionfileupload_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dkbtransaction",
            name="purpose",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dkbtransaction",
            name="status",
            field=models.CharField(max_length=64),
        ),
    ]
