# Generated by Django 5.1.4 on 2025-01-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0004_dkbtransaction_purpose_alter_dkbtransaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dkbtransaction",
            name="purpose",
            field=models.TextField(),
        ),
    ]
